---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-161 D} | Spring 2025}
  \fancyhead[RO,R]{\textbf{W 2/5 Worksheet} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
nocite: '@*'
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** 

> You must submit your worksheet individually by end-of-class or end-of-day. Your name must exist in your worksheet and the names of your collaborators.

Worksheets are marked mostly on completion, and partially on correctness. It will be marked either pass or fail, there will no detailed feedback on worksheets, and no opportunities for revisions and make-up.
\noindent\rule{\textwidth}{1pt}

## Identify the Shape of Disribution

### 1. Distribution Shapes of Variables

Based on your intuition, describe the distribution shape (modality and skewness) of the following numerical variables. Explain your reasoning. You may add an approximate sketch of the distribution. 

a. weights of adult females
\vfill
  
b. salaries of a random sample of people from North Carolina
\vfill

\newpage

c. house prices
\vfill
  
d. birthdays of classmates (day of the month)
\vfill

## **References**

::: {#refs}
:::
